### ISSUE TITLE
website font cuts off paint editor text boxes

### ISSUE THREAD

**Issue by ksdavidc** [Looky1173/Scratch-Auth-Client#21]
This will be arcane. 

Steps to reproduce:
1. (not necessary but for completeness) turn off all plugins/addons
2. turn on website mode add any font
3. new project, new sprite
4. svg mode, text box, add some text, of not minimal length, single line
5. a bit of text disappears at the right.

1. turn off website mode
2. save/reload
3. return to costume, and move/center the costume. 
4. the missing text reappears.

video: the real action starts around 20 seconds in....

https://github.com/Looky1173/Scratch-Auth-Client/assets/62230004/72e1f8d0-7d46-44bc-aee9-b90e16f84e1e

**Comment by ksdavidc** [comment]
Note that this is fussy. For example, if there are other elements in the costume to the right of the cutoff, the cutoff text reappears. Likewise if the text is more than one line, and other such hijinks...

**Comment by yoyomonem** [comment]
This issue is unrelated to Scratch Auth. I have noticed that ScratchTools is pictured in the Untitled.mov that you uploaded with the issue, so how about you report this to the ScratchTools GitHub repo instead?
<sup>No, I'm not @Looky1173, but I'll tell @Looky1173 to delete this issue. Meanwhile, try to save the Markdown in your issue for putting in the ScratchTools repo before @Looky1173 deletes this issue.</sup>

**Comment by ksdavidc** [comment]
My apologies. I think I just got my tabs mixed up, and thought I was posting on Scratchtools. My mistake. I have moved this to there, so feel free to delete.
